apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: meureplik7
spec: 
  replicas: 5 
  selector: 
    matchLabels: 
      app: web
  template: 
    metadata: 
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: parrot02/conversao-temperatura:latest
          ports:
          - containerPort: 80 